# Generated by Django 4.1.2 on 2022-12-23 13:07

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_state', models.CharField(blank=True, help_text='State', max_length=144, null=True)),
                ('enquiry_city', models.CharField(blank=True, help_text='City/LGA', max_length=144, null=True)),
                ('enquiry_Address', models.CharField(blank=True, help_text='Local Area/Bustops/Park', max_length=144, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='from_user', unique_with=('enquiry_date',))),
                ('enquiry_property_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Land', 'Land'), ('BQ', 'Bq'), ('Terrace', 'Terrace'), ('Semi Detached', 'Semi Detached'), ('Fully Detached', 'Fully Detached'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Type', max_length=144, null=True)),
                ('enquiry_property_status', models.CharField(blank=True, choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale'), ('Auction', 'Auction'), ('Sold', 'Sold'), ('Rented', 'Rented')], default='Status', max_length=144, null=True)),
                ('enquiry_description', models.TextField(blank=True, help_text='Tell us more about what you need.', null=True)),
                ('enquiry_budget_min', models.DecimalField(decimal_places=2, help_text='Your Minimum Budget', max_digits=10)),
                ('enquiry_budget_max', models.DecimalField(decimal_places=2, help_text='Your Maximum Budget', max_digits=10)),
                ('enquiry_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='0.00', max_digits=10, null=True)),
                ('enquiry_on_promo', models.BooleanField(default=True)),
                ('inspection_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Open', 'Open')], default='Open', max_length=100, null=True)),
                ('enquiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_enquiries', to=settings.AUTH_USER_MODEL)),
                ('to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_enquiries', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ('-enquiry_date',),
            },
        ),
    ]
