# Generated by Django 4.1.2 on 2022-12-23 13:07

import apps.profiles.models
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='user', unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('bio', models.TextField(default='Say something about yourself', verbose_name='About me')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.upload_dir)),
                ('country', django_countries.fields.CountryField(blank=True, default='NG', max_length=2, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address')),
                ('birth_day', models.DateTimeField(blank=True, null=True)),
                ('conversations', models.ManyToManyField(blank=True, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('favorite_properties', models.ManyToManyField(blank=True, to='properties.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
