# Generated by Django 4.1.2 on 2022-12-24 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inboxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='msg_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
