# Generated by Django 4.1.2 on 2022-12-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0002_alter_inboxmessage_msg_sender'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='agent_message',
        ),
        migrations.AddField(
            model_name='notification',
            name='inbox_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_msg_notification', to='inboxes.inboxmessage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Transaction_Message'), (2, 'Property_Message'), (3, 'Inbox_Message'), (4, 'Enquiry_message'), (5, 'Review_Message'), (6, 'Property_Comment')]),
        ),
    ]
